// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("AccessorialRules", Schema = "rating")]
[Index("ContractVersionId", "IsEnabled", "Priority", Name = "IX_AccessorialRules_ByVersion")]
public partial class AccessorialRule
{
    [Key]
    public long AccessorialRuleId { get; set; }

    public long ContractVersionId { get; set; }

    public long AccessorialId { get; set; }

    [StringLength(200)]
    public string RuleName { get; set; } = null!;

    public string ConditionExpression { get; set; } = null!;

    [StringLength(20)]
    public string? OverrideCalcType { get; set; }

    public string? OverrideExpression { get; set; }

    [StringLength(20)]
    public string StackingPolicy { get; set; } = null!;

    [StringLength(50)]
    public string? ExclusiveGroupKey { get; set; }

    public int Priority { get; set; }

    public bool IsEnabled { get; set; }

    [ForeignKey("AccessorialId")]
    [InverseProperty("AccessorialRules")]
    public virtual Accessorial Accessorial { get; set; } = null!;

    [ForeignKey("ContractVersionId")]
    [InverseProperty("AccessorialRules")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}