// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("Accessorials", Schema = "rating")]
[Index("Code", Name = "UQ_Accessorials_Code", IsUnique = true)]
public partial class Accessorial
{
    [Key]
    public long AccessorialId { get; set; }

    [StringLength(50)]
    public string Code { get; set; } = null!;

    [StringLength(200)]
    public string? Description { get; set; }

    public string? ModeApplicabilityJson { get; set; }

    [InverseProperty("Accessorial")]
    public virtual ICollection<AccessorialRule> AccessorialRules { get; set; } = new List<AccessorialRule>();

    [InverseProperty("Accessorial")]
    public virtual ICollection<ContractAccessorialCharge> ContractAccessorialCharges { get; set; } = new List<ContractAccessorialCharge>();
}