// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("Accounts", Schema = "rating")]
[Index("AccountCode", Name = "UQ_Accounts_AccountCode", IsUnique = true)]
public partial class Account
{
    [Key]
    public long AccountId { get; set; }

    [StringLength(50)]
    public string AccountCode { get; set; } = null!;

    [StringLength(200)]
    public string Name { get; set; } = null!;

    [StringLength(20)]
    public string Status { get; set; } = null!;

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    [InverseProperty("Account")]
    public virtual ICollection<RateQuote> RateQuotes { get; set; } = new List<RateQuote>();
}