// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("CacheNamespaces", Schema = "rating")]
[Index("UpdatedAt", Name = "IX_CacheNamespaces_UpdatedAt", AllDescending = true)]
public partial class CacheNamespace
{
    [Key]
    [StringLength(200)]
    public string NamespaceKey { get; set; } = null!;

    public long VersionNo { get; set; }

    [Precision(3)]
    public DateTime UpdatedAt { get; set; }

    [StringLength(450)]
    [Unicode(false)]
    public string? UpdatedBy { get; set; }

    [StringLength(500)]
    public string? Note { get; set; }
}