// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("ContractStatusHistory", Schema = "rating")]
[Index("ContractId", "ChangedAt", Name = "IX_ContractStatusHistory_ContractId_ChangedAt", IsDescending = new[] { false, true })]
public partial class ContractStatusHistory
{
    [Key]
    public long ContractStatusHistoryId { get; set; }

    public long ContractId { get; set; }

    public long ContractVersionId { get; set; }

    [Precision(3)]
    public DateTime ChangedAt { get; set; }

    [StringLength(20)]
    public string? FromStatus { get; set; }

    [StringLength(20)]
    public string ToStatus { get; set; } = null!;

    [StringLength(450)]
    [Unicode(false)]
    public string UserId { get; set; } = null!;

    public string? Note { get; set; }

    [ForeignKey("ContractId")]
    [InverseProperty("ContractStatusHistories")]
    public virtual Contract Contract { get; set; } = null!;

    [ForeignKey("ContractVersionId")]
    [InverseProperty("ContractStatusHistories")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}