// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("ContractLaneEligibility", Schema = "rating")]
[Index("Mode", "LaneKeyHash", Name = "IX_CLE_Mode_LaneKeyHash")]
[Index("ContractVersionId", "Mode", "OriginZoneId", "DestZoneId", "OriginRegionId", "DestRegionId", "EquipmentType", "OriginPort", "DestPort", "ContainerType", Name = "UX_CLE_UniqueLanePerVersion", IsUnique = true)]
[Index("ContractVersionId", "Mode", "LaneKeyHash", Name = "UX_CLE_Version_Mode_LaneKeyHash", IsUnique = true)]
public partial class ContractLaneEligibility
{
    [Key]
    public long ContractLaneEligibilityId { get; set; }

    public long ContractVersionId { get; set; }

    [StringLength(10)]
    public string Mode { get; set; } = null!;

    public int? OriginZoneId { get; set; }

    public int? DestZoneId { get; set; }

    public int? OriginRegionId { get; set; }

    public int? DestRegionId { get; set; }

    [StringLength(30)]
    public string? EquipmentType { get; set; }

    [StringLength(10)]
    public string? OriginPort { get; set; }

    [StringLength(10)]
    public string? DestPort { get; set; }

    [StringLength(20)]
    public string? ContainerType { get; set; }

    public bool? AllowsMultiStop { get; set; }

    public int? MaxStops { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [StringLength(300)]
    public string LaneKeyString { get; set; } = null!;

    [MaxLength(32)]
    public byte[] LaneKeyHash { get; set; } = null!;

    [ForeignKey("ContractVersionId")]
    [InverseProperty("ContractLaneEligibilities")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}