// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("ContractVersions", Schema = "rating")]
[Index("ContractId", "PublishStatus", "EffectiveStart", "EffectiveEnd", Name = "IX_ContractVersions_ActivePublished")]
[Index("ContractId", "VersionNo", Name = "UQ_ContractVersions", IsUnique = true)]
public partial class ContractVersion
{
    [Key]
    public long ContractVersionId { get; set; }

    public long ContractId { get; set; }

    public int VersionNo { get; set; }

    public DateOnly EffectiveStart { get; set; }

    public DateOnly EffectiveEnd { get; set; }

    [StringLength(20)]
    public string PublishStatus { get; set; } = null!;

    [StringLength(100)]
    public string? CreatedBy { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [Precision(3)]
    public DateTime? PublishedAt { get; set; }

    [InverseProperty("ContractVersion")]
    public virtual ICollection<AccessorialRule> AccessorialRules { get; set; } = new List<AccessorialRule>();

    [ForeignKey("ContractId")]
    [InverseProperty("ContractVersions")]
    public virtual Contract Contract { get; set; } = null!;

    [InverseProperty("ContractVersion")]
    public virtual ICollection<ContractAccessorialCharge> ContractAccessorialCharges { get; set; } = new List<ContractAccessorialCharge>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<ContractFuelRule> ContractFuelRules { get; set; } = new List<ContractFuelRule>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<ContractLaneEligibility> ContractLaneEligibilities { get; set; } = new List<ContractLaneEligibility>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<ContractStatusHistory> ContractStatusHistories { get; set; } = new List<ContractStatusHistory>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<FclContainerRate> FclContainerRates { get; set; } = new List<FclContainerRate>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<FtlLaneRate> FtlLaneRates { get; set; } = new List<FtlLaneRate>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<LclRate> LclRates { get; set; } = new List<LclRate>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<LtlBaseRate> LtlBaseRates { get; set; } = new List<LtlBaseRate>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<LtlDiscountRule> LtlDiscountRules { get; set; } = new List<LtlDiscountRule>();

    [InverseProperty("ContractVersion")]
    public virtual ICollection<RateQuoteResult> RateQuoteResults { get; set; } = new List<RateQuoteResult>();
}