// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("ContractFuelRules", Schema = "rating")]
[Index("ContractVersionId", Name = "IX_ContractFuelRules_ByVersion")]
public partial class ContractFuelRule
{
    [Key]
    public long ContractFuelRuleId { get; set; }

    public long ContractVersionId { get; set; }

    public long FuelScheduleId { get; set; }

    [StringLength(20)]
    public string ApplyTo { get; set; } = null!;

    [StringLength(20)]
    public string CalcMethod { get; set; } = null!;

    public string? FormulaExpression { get; set; }

    public string? RoundingJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("ContractFuelRules")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;

    [ForeignKey("FuelScheduleId")]
    [InverseProperty("ContractFuelRules")]
    public virtual FuelSchedule FuelSchedule { get; set; } = null!;
}