// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("ContractAccessorialCharges", Schema = "rating")]
[Index("ContractVersionId", "AccessorialId", Name = "UX_CAC_VersionAccessorial", IsUnique = true)]
public partial class ContractAccessorialCharge
{
    [Key]
    public long ContractAccessorialChargeId { get; set; }

    public long ContractVersionId { get; set; }

    public long AccessorialId { get; set; }

    [StringLength(20)]
    public string CalcType { get; set; } = null!;

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? FlatAmount { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? PercentValue { get; set; }

    public string? FormulaExpression { get; set; }

    public string? TierTableJson { get; set; }

    [StringLength(30)]
    public string ApplyTo { get; set; } = null!;

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MinAmount { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MaxAmount { get; set; }

    [ForeignKey("AccessorialId")]
    [InverseProperty("ContractAccessorialCharges")]
    public virtual Accessorial Accessorial { get; set; } = null!;

    [ForeignKey("ContractVersionId")]
    [InverseProperty("ContractAccessorialCharges")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}