// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("Contracts", Schema = "rating")]
[Index("AccountId", "Mode", "ProviderId", Name = "IX_Contracts_AccountMode")]
public partial class Contract
{
    [Key]
    public long ContractId { get; set; }

    public long? AccountId { get; set; }

    public long ProviderId { get; set; }

    [StringLength(10)]
    public string Mode { get; set; } = null!;

    [StringLength(200)]
    public string Name { get; set; } = null!;

    [StringLength(3)]
    public string CurrencyCode { get; set; } = null!;

    [StringLength(20)]
    public string Status { get; set; } = null!;

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Contracts")]
    public virtual Account? Account { get; set; }

    [InverseProperty("Contract")]
    public virtual ICollection<ContractStatusHistory> ContractStatusHistories { get; set; } = new List<ContractStatusHistory>();

    [InverseProperty("Contract")]
    public virtual ICollection<ContractVersion> ContractVersions { get; set; } = new List<ContractVersion>();

    [ForeignKey("ProviderId")]
    [InverseProperty("Contracts")]
    public virtual Provider Provider { get; set; } = null!;

    [InverseProperty("Contract")]
    public virtual ICollection<RateQuoteResult> RateQuoteResults { get; set; } = new List<RateQuoteResult>();
}