// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("EdiChargeCodes", Schema = "rating")]
[Index("Standard", "Code", Name = "UQ_EdiChargeCodes", IsUnique = true)]
public partial class EdiChargeCode
{
    [Key]
    public long EdiChargeCodeId { get; set; }

    [StringLength(10)]
    public string Standard { get; set; } = null!;

    [StringLength(50)]
    public string Code { get; set; } = null!;

    [StringLength(200)]
    public string? Description { get; set; }

    [StringLength(30)]
    public string CanonicalChargeType { get; set; } = null!;

    [StringLength(50)]
    public string? DefaultAccessorialCode { get; set; }
}