// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("FclContainerRates", Schema = "rating")]
[Index("ContractVersionId", "OriginPort", "DestPort", "ContainerType", Name = "IX_FclContainerRates_Lookup")]
public partial class FclContainerRate
{
    [Key]
    public long FclContainerRateId { get; set; }

    public long ContractVersionId { get; set; }

    [StringLength(10)]
    public string OriginPort { get; set; } = null!;

    [StringLength(10)]
    public string DestPort { get; set; } = null!;

    [StringLength(20)]
    public string ContainerType { get; set; } = null!;

    [Column(TypeName = "decimal(18, 6)")]
    public decimal BaseRate { get; set; }

    public int? FreeDays { get; set; }

    public string? ConstraintsJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("FclContainerRates")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}