// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("FtlLaneRates", Schema = "rating")]
[Index("ContractVersionId", "OriginRegionId", "DestRegionId", "EquipmentType", Name = "IX_FtlLaneRates_Lookup")]
public partial class FtlLaneRate
{
    [Key]
    public long FtlLaneRateId { get; set; }

    public long ContractVersionId { get; set; }

    public int OriginRegionId { get; set; }

    public int DestRegionId { get; set; }

    [StringLength(30)]
    public string EquipmentType { get; set; } = null!;

    [StringLength(20)]
    public string RateType { get; set; } = null!;

    [Column(TypeName = "decimal(18, 6)")]
    public decimal RateValue { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MinimumCharge { get; set; }

    public int IncludedStops { get; set; }

    public string? ConstraintsJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("FtlLaneRates")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}