// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("FuelScheduleRows", Schema = "rating")]
[Index("FuelScheduleId", "EffectiveStart", "EffectiveEnd", "IndexMin", "IndexMax", Name = "IX_FuelScheduleRows_Lookup")]
public partial class FuelScheduleRow
{
    [Key]
    public long FuelScheduleRowId { get; set; }

    public long FuelScheduleId { get; set; }

    public DateOnly EffectiveStart { get; set; }

    public DateOnly EffectiveEnd { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? IndexMin { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? IndexMax { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal FuelValue { get; set; }

    [ForeignKey("FuelScheduleId")]
    [InverseProperty("FuelScheduleRows")]
    public virtual FuelSchedule FuelSchedule { get; set; } = null!;
}