// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("FuelSchedules", Schema = "rating")]
public partial class FuelSchedule
{
    [Key]
    public long FuelScheduleId { get; set; }

    [StringLength(200)]
    public string Name { get; set; } = null!;

    [StringLength(20)]
    public string IndexType { get; set; } = null!;

    [StringLength(20)]
    public string Unit { get; set; } = null!;

    [StringLength(500)]
    public string? Notes { get; set; }

    [InverseProperty("FuelSchedule")]
    public virtual ICollection<ContractFuelRule> ContractFuelRules { get; set; } = new List<ContractFuelRule>();

    [InverseProperty("FuelSchedule")]
    public virtual ICollection<FuelScheduleRow> FuelScheduleRows { get; set; } = new List<FuelScheduleRow>();
}