// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("GeoZipZone", Schema = "rating")]
[Index("PostalCode", "CountryCode", Name = "IX_GeoZipZone_PostalCountry")]
[Index("PostalCode", "CountryCode", Name = "UQ_GeoZipZone", IsUnique = true)]
public partial class GeoZipZone
{
    [Key]
    public long GeoZipZoneId { get; set; }

    [StringLength(20)]
    public string PostalCode { get; set; } = null!;

    [StringLength(2)]
    public string CountryCode { get; set; } = null!;

    public int? ZoneId { get; set; }

    public int? RegionId { get; set; }

    public int? MetroId { get; set; }

    [Precision(3)]
    public DateTime UpdatedAt { get; set; }
}