// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("LclRates", Schema = "rating")]
[Index("ContractVersionId", "OriginPort", "DestPort", "RateBasis", Name = "IX_LclRates_Lookup")]
public partial class LclRate
{
    [Key]
    public long LclRateId { get; set; }

    public long ContractVersionId { get; set; }

    [StringLength(10)]
    public string OriginPort { get; set; } = null!;

    [StringLength(10)]
    public string DestPort { get; set; } = null!;

    [StringLength(10)]
    public string RateBasis { get; set; } = null!;

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? RatePerWm { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? RatePerLb { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal MinimumCharge { get; set; }

    public string? BreakpointsJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("LclRates")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}