// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("Locations", Schema = "rating")]
public partial class Location
{
    [Key]
    public long LocationId { get; set; }

    [StringLength(200)]
    public string? Name { get; set; }

    [StringLength(200)]
    public string? Address1 { get; set; }

    [StringLength(200)]
    public string? Address2 { get; set; }

    [StringLength(100)]
    public string? City { get; set; }

    [StringLength(50)]
    public string? State { get; set; }

    [StringLength(20)]
    public string? PostalCode { get; set; }

    [StringLength(2)]
    public string CountryCode { get; set; } = null!;

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Longitude { get; set; }

    [Column("UNLocode")]
    [StringLength(10)]
    public string? Unlocode { get; set; }

    [StringLength(5)]
    public string? AirportCode { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }
}