// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("LtlBaseRates", Schema = "rating")]
[Index("ContractVersionId", "OriginZoneId", "DestZoneId", "NmfcClass", "WeightMinLbs", "WeightMaxLbs", Name = "IX_LtlBaseRates_Lookup")]
public partial class LtlBaseRate
{
    [Key]
    public long LtlBaseRateId { get; set; }

    public long ContractVersionId { get; set; }

    public int OriginZoneId { get; set; }

    public int DestZoneId { get; set; }

    public int NmfcClass { get; set; }

    public int WeightMinLbs { get; set; }

    public int WeightMaxLbs { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal RatePerCwt { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MinimumCharge { get; set; }

    public string? DeficitRuleJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("LtlBaseRates")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}