// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("LtlDiscountRules", Schema = "rating")]
[Index("ContractVersionId", "NmfcClass", Name = "IX_LtlDiscountRules_ByVersion")]
public partial class LtlDiscountRule
{
    [Key]
    public long LtlDiscountRuleId { get; set; }

    public long ContractVersionId { get; set; }

    public int? NmfcClass { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal DiscountPercent { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MinChargeOverride { get; set; }

    public string? ConditionsJson { get; set; }

    [ForeignKey("ContractVersionId")]
    [InverseProperty("LtlDiscountRules")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;
}