// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("Providers", Schema = "rating")]
[Index("ProviderCode", Name = "UQ_Providers_ProviderCode", IsUnique = true)]
public partial class Provider
{
    [Key]
    public long ProviderId { get; set; }

    [StringLength(50)]
    public string ProviderCode { get; set; } = null!;

    [StringLength(200)]
    public string Name { get; set; } = null!;

    [StringLength(20)]
    public string Status { get; set; } = null!;

    public string? ModeCapabilitiesJson { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Provider")]
    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    [InverseProperty("Provider")]
    public virtual ICollection<RateQuoteResult> RateQuoteResults { get; set; } = new List<RateQuoteResult>();
}