// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("RateQuoteResults", Schema = "rating")]
[Index("RateQuoteId", "Rank", Name = "IX_RateQuoteResults_ByQuoteRank")]
public partial class RateQuoteResult
{
    [Key]
    public long RateQuoteResultId { get; set; }

    public long RateQuoteId { get; set; }

    public long ProviderId { get; set; }

    public long ContractId { get; set; }

    public long ContractVersionId { get; set; }

    public int Rank { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal TotalAmount { get; set; }

    public int? TransitDays { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("ContractId")]
    [InverseProperty("RateQuoteResults")]
    public virtual Contract Contract { get; set; } = null!;

    [ForeignKey("ContractVersionId")]
    [InverseProperty("RateQuoteResults")]
    public virtual ContractVersion ContractVersion { get; set; } = null!;

    [ForeignKey("ProviderId")]
    [InverseProperty("RateQuoteResults")]
    public virtual Provider Provider { get; set; } = null!;

    [ForeignKey("RateQuoteId")]
    [InverseProperty("RateQuoteResults")]
    public virtual RateQuote RateQuote { get; set; } = null!;

    [InverseProperty("RateQuoteResult")]
    public virtual ICollection<RateQuoteChargeLine> RateQuoteChargeLines { get; set; } = new List<RateQuoteChargeLine>();
}