// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("RateQuotes", Schema = "rating")]
public partial class RateQuote
{
    [Key]
    public long RateQuoteId { get; set; }

    public Guid RequestId { get; set; }

    public long AccountId { get; set; }

    [StringLength(10)]
    public string Mode { get; set; } = null!;

    [StringLength(3)]
    public string CurrencyCode { get; set; } = null!;

    public DateOnly RateDate { get; set; }

    [Precision(3)]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("RateQuotes")]
    public virtual Account Account { get; set; } = null!;

    [InverseProperty("RateQuote")]
    public virtual ICollection<RateQuoteResult> RateQuoteResults { get; set; } = new List<RateQuoteResult>();
}