// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Models;

[Table("RateQuoteChargeLines", Schema = "rating")]
[Index("RateQuoteResultId", "SequenceNo", Name = "IX_RateQuoteChargeLines_ResultSeq")]
public partial class RateQuoteChargeLine
{
    [Key]
    public long RateQuoteChargeLineId { get; set; }

    public long RateQuoteResultId { get; set; }

    public int SequenceNo { get; set; }

    [StringLength(30)]
    public string CanonicalChargeType { get; set; } = null!;

    [StringLength(50)]
    public string? AccessorialCode { get; set; }

    [StringLength(10)]
    public string? EdiStandard { get; set; }

    [StringLength(50)]
    public string? EdiChargeCode { get; set; }

    [StringLength(200)]
    public string? Description { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Quantity { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Rate { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal Amount { get; set; }

    [StringLength(30)]
    public string? ApplyTo { get; set; }

    public int? StopSequence { get; set; }

    public int? LegSequence { get; set; }

    public string? DetailJson { get; set; }

    [ForeignKey("RateQuoteResultId")]
    [InverseProperty("RateQuoteChargeLines")]
    public virtual RateQuoteResult RateQuoteResult { get; set; } = null!;
}