// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BTSS.Rating.Models
{
    public partial class usp_GetCandidateContractVersions_ByLaneHashResult
    {
        public long ContractVersionId { get; set; }
        public long ContractId { get; set; }
        public long ProviderId { get; set; }
        [StringLength(50)]
        public string ProviderCode { get; set; } = default!;
        public long? AccountId { get; set; }
    }
}
