// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BTSS.Rating.Models
{
    public partial class usp_GetCacheNamespaceVersionResult
    {
        [StringLength(200)]
        public string NamespaceKey { get; set; } = default!;
        public long VersionNo { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
