// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BTSS.Rating.Models
{
    public partial class usp_GetCacheNamespaceVersionsForQuoteResult
    {
        public long? AccountId { get; set; }
        [StringLength(10)]
        public string? Mode { get; set; }
        public long CandidatesAccountVersion { get; set; }
        public long RatesAccountVersion { get; set; }
        public long CandidatesPublicVersion { get; set; }
        public long RatesPublicVersion { get; set; }
        public DateTime CandidatesAccountUpdatedAt { get; set; }
        public DateTime RatesAccountUpdatedAt { get; set; }
        public DateTime CandidatesPublicUpdatedAt { get; set; }
        public DateTime RatesPublicUpdatedAt { get; set; }
    }
}
