// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using BTSS.Rating.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BTSS.Rating.Persistence
{
    public partial interface IRatingDbContextProcedures
    {
        Task<List<usp_BumpCacheNamespaceResult>?> usp_BumpCacheNamespaceAsync(string? namespaceKey, string? updatedBy, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_BumpNamespacesForContractResult>?> usp_BumpNamespacesForContractAsync(long? contractId, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_BumpNamespacesForContractVersionResult>?> usp_BumpNamespacesForContractVersionAsync(long? contractVersionId, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCacheNamespaceVersionResult>?> usp_GetCacheNamespaceVersionAsync(string? namespaceKey, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCacheNamespaceVersionsForQuoteResult>?> usp_GetCacheNamespaceVersionsForQuoteAsync(long? accountId, string? mode, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCandidateContractVersionsResult>?> usp_GetCandidateContractVersionsAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, string? equipmentType, string? containerType, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? originPort, string? destPort, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCandidateContractVersions_ByLaneHashResult>?> usp_GetCandidateContractVersions_ByLaneHashAsync(long? accountId, string? mode, DateOnly? rateDate, byte[]? laneKeyHash, string? laneKeyString, string? providerIncludeCsv, string? providerExcludeCsv, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCandidateContractVersions_FastResult>?> usp_GetCandidateContractVersions_FastAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, string? equipmentType, string? containerType, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? originPort, string? destPort, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_GetCandidateContractVersions_HashFastResult>?> usp_GetCandidateContractVersions_HashFastAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? equipmentType, string? originPort, string? destPort, string? containerType, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> usp_PublishContractVersionAsync(long? contractVersionId, string? publishedBy, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<usp_PublishContractVersion_HashResult>?> usp_PublishContractVersion_HashAsync(long? contractVersionId, string? publishedBy, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> usp_RebuildContractLaneEligibilityAsync(long? contractVersionId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> usp_RebuildContractLaneEligibility_HashAsync(long? contractVersionId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
