// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BTSS.Rating.Models;
using Microsoft.EntityFrameworkCore;

namespace BTSS.Rating.Persistence;

public partial class RatingDbContext : DbContext
{
    public RatingDbContext(DbContextOptions<RatingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Accessorial> Accessorials { get; set; }

    public virtual DbSet<AccessorialRule> AccessorialRules { get; set; }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<CacheNamespace> CacheNamespaces { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<ContractAccessorialCharge> ContractAccessorialCharges { get; set; }

    public virtual DbSet<ContractFuelRule> ContractFuelRules { get; set; }

    public virtual DbSet<ContractLaneEligibility> ContractLaneEligibilities { get; set; }

    public virtual DbSet<ContractStatusHistory> ContractStatusHistories { get; set; }

    public virtual DbSet<ContractVersion> ContractVersions { get; set; }

    public virtual DbSet<EdiChargeCode> EdiChargeCodes { get; set; }

    public virtual DbSet<FclContainerRate> FclContainerRates { get; set; }

    public virtual DbSet<FtlLaneRate> FtlLaneRates { get; set; }

    public virtual DbSet<FuelSchedule> FuelSchedules { get; set; }

    public virtual DbSet<FuelScheduleRow> FuelScheduleRows { get; set; }

    public virtual DbSet<GeoZipZone> GeoZipZones { get; set; }

    public virtual DbSet<LclRate> LclRates { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<LtlBaseRate> LtlBaseRates { get; set; }

    public virtual DbSet<LtlDiscountRule> LtlDiscountRules { get; set; }

    public virtual DbSet<Provider> Providers { get; set; }

    public virtual DbSet<RateQuote> RateQuotes { get; set; }

    public virtual DbSet<RateQuoteChargeLine> RateQuoteChargeLines { get; set; }

    public virtual DbSet<RateQuoteResult> RateQuoteResults { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccessorialRule>(entity =>
        {
            entity.ToTable("AccessorialRules", "rating", tb => tb.HasTrigger("trg_AccessorialRules_NoOverlap"));

            entity.Property(e => e.IsEnabled).HasDefaultValue(true, "DF_AccessorialRules_IsEnabled");
            entity.Property(e => e.Priority).HasDefaultValue(100, "DF_AccessorialRules_Priority");
            entity.Property(e => e.StackingPolicy).HasDefaultValue("ADD", "DF_AccessorialRules_Stacking");

            entity.HasOne(d => d.Accessorial).WithMany(p => p.AccessorialRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AR_Accessorials");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.AccessorialRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AR_ContractVersions");
        });

        modelBuilder.Entity<Account>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_Accounts_CreatedAt");
            entity.Property(e => e.Status).HasDefaultValue("ACTIVE", "DF_Accounts_Status");
        });

        modelBuilder.Entity<CacheNamespace>(entity =>
        {
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_CacheNamespaces_UpdatedAt");
            entity.Property(e => e.VersionNo).HasDefaultValue(1L, "DF_CacheNamespaces_VersionNo");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.ToTable("Contracts", "rating", tb => tb.HasTrigger("trg_Contracts_StatusHistory"));

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_Contracts_CreatedAt");
            entity.Property(e => e.CurrencyCode).HasDefaultValue("USD", "DF_Contracts_Currency");
            entity.Property(e => e.Status).HasDefaultValue("ACTIVE", "DF_Contracts_Status");

            entity.HasOne(d => d.Account).WithMany(p => p.Contracts).HasConstraintName("FK_Contracts_Accounts");

            entity.HasOne(d => d.Provider).WithMany(p => p.Contracts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Contracts_Providers");
        });

        modelBuilder.Entity<ContractAccessorialCharge>(entity =>
        {
            entity.ToTable("ContractAccessorialCharges", "rating", tb => tb.HasTrigger("trg_ContractAccessorialCharges_NoOverlap"));

            entity.HasOne(d => d.Accessorial).WithMany(p => p.ContractAccessorialCharges)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAC_Accessorials");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.ContractAccessorialCharges)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAC_ContractVersions");
        });

        modelBuilder.Entity<ContractFuelRule>(entity =>
        {
            entity.ToTable("ContractFuelRules", "rating", tb => tb.HasTrigger("trg_ContractFuelRules_NoOverlap"));

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.ContractFuelRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractFuelRules_ContractVersions");

            entity.HasOne(d => d.FuelSchedule).WithMany(p => p.ContractFuelRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractFuelRules_FuelSchedules");
        });

        modelBuilder.Entity<ContractLaneEligibility>(entity =>
        {
            entity.HasIndex(e => new { e.Mode, e.OriginPort, e.DestPort, e.ContainerType, e.ContractVersionId }, "IX_CLE_FCL").HasFilter("([Mode]='FCL')");

            entity.HasIndex(e => new { e.Mode, e.OriginRegionId, e.DestRegionId, e.EquipmentType, e.ContractVersionId }, "IX_CLE_FTL").HasFilter("([Mode]='FTL')");

            entity.HasIndex(e => new { e.Mode, e.OriginPort, e.DestPort, e.ContractVersionId }, "IX_CLE_LCL").HasFilter("([Mode]='LCL')");

            entity.HasIndex(e => new { e.Mode, e.OriginZoneId, e.DestZoneId, e.ContractVersionId }, "IX_CLE_LTL").HasFilter("([Mode]='LTL')");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_CLE_CreatedAt");
            entity.Property(e => e.LaneKeyHash)
                .IsFixedLength()
                .HasDefaultValueSql("(0x00)", "DF_CLE_LaneKeyHash");
            entity.Property(e => e.LaneKeyString).HasDefaultValue("", "DF_CLE_LaneKeyString");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.ContractLaneEligibilities)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CLE_ContractVersions");
        });

        modelBuilder.Entity<ContractStatusHistory>(entity =>
        {
            entity.Property(e => e.ChangedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_ContractStatusHistory_ChangedAt");

            entity.HasOne(d => d.Contract).WithMany(p => p.ContractStatusHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractStatusHistory_Contracts");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.ContractStatusHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractStatusHistory_ContractVersion");
        });

        modelBuilder.Entity<ContractVersion>(entity =>
        {
            entity.HasIndex(e => new { e.ContractId, e.EffectiveStart, e.EffectiveEnd }, "IX_ContractVersions_PublishedOnly").HasFilter("([PublishStatus]='PUBLISHED')");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_ContractVersions_CreatedAt");
            entity.Property(e => e.PublishStatus).HasDefaultValue("DRAFT", "DF_ContractVersions_PublishStatus");

            entity.HasOne(d => d.Contract).WithMany(p => p.ContractVersions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContractVersions_Contracts");
        });

        modelBuilder.Entity<FclContainerRate>(entity =>
        {
            entity.ToTable("FclContainerRates", "rating", tb => tb.HasTrigger("trg_FclContainerRates_NoOverlap"));

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.FclContainerRates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FclContainerRates_ContractVersions");
        });

        modelBuilder.Entity<FtlLaneRate>(entity =>
        {
            entity.ToTable("FtlLaneRates", "rating", tb => tb.HasTrigger("trg_FtlLaneRates_NoOverlap"));

            entity.Property(e => e.IncludedStops).HasDefaultValue(2, "DF_FtlLaneRates_IncludedStops");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.FtlLaneRates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FtlLaneRates_ContractVersions");
        });

        modelBuilder.Entity<FuelScheduleRow>(entity =>
        {
            entity.HasOne(d => d.FuelSchedule).WithMany(p => p.FuelScheduleRows)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FuelScheduleRows_FuelSchedules");
        });

        modelBuilder.Entity<GeoZipZone>(entity =>
        {
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_GeoZipZone_UpdatedAt");
        });

        modelBuilder.Entity<LclRate>(entity =>
        {
            entity.ToTable("LclRates", "rating", tb => tb.HasTrigger("trg_LclRates_NoOverlap"));

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.LclRates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LclRates_ContractVersions");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_Locations_CreatedAt");
        });

        modelBuilder.Entity<LtlBaseRate>(entity =>
        {
            entity.ToTable("LtlBaseRates", "rating", tb => tb.HasTrigger("trg_LtlBaseRates_NoOverlap"));

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.LtlBaseRates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LtlBaseRates_ContractVersions");
        });

        modelBuilder.Entity<LtlDiscountRule>(entity =>
        {
            entity.ToTable("LtlDiscountRules", "rating", tb => tb.HasTrigger("trg_LtlDiscountRules_NoOverlap"));

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.LtlDiscountRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LtlDiscountRules_ContractVersions");
        });

        modelBuilder.Entity<Provider>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_Providers_CreatedAt");
            entity.Property(e => e.Status).HasDefaultValue("ACTIVE", "DF_Providers_Status");
        });

        modelBuilder.Entity<RateQuote>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_RateQuotes_CreatedAt");

            entity.HasOne(d => d.Account).WithMany(p => p.RateQuotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RateQuotes_Accounts");
        });

        modelBuilder.Entity<RateQuoteChargeLine>(entity =>
        {
            entity.HasOne(d => d.RateQuoteResult).WithMany(p => p.RateQuoteChargeLines)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RQCL_Result");
        });

        modelBuilder.Entity<RateQuoteResult>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_RateQuoteResults_CreatedAt");

            entity.HasOne(d => d.Contract).WithMany(p => p.RateQuoteResults)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RQR_Contracts");

            entity.HasOne(d => d.ContractVersion).WithMany(p => p.RateQuoteResults)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RQR_ContractVersions");

            entity.HasOne(d => d.Provider).WithMany(p => p.RateQuoteResults)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RQR_Providers");

            entity.HasOne(d => d.RateQuote).WithMany(p => p.RateQuoteResults)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RQR_RateQuotes");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}