// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using BTSS.Rating.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BTSS.Rating.Persistence
{
    public partial class RatingDbContext
    {
        private IRatingDbContextProcedures? _procedures;

        public virtual IRatingDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RatingDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRatingDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RatingDbContextProcedures : IRatingDbContextProcedures
    {
        private readonly RatingDbContext _context;

        public RatingDbContextProcedures(RatingDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_BumpCacheNamespaceResult>?> usp_BumpCacheNamespaceAsync(string? namespaceKey, string? updatedBy, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NamespaceKey",
                    Size = 400,
                    Value = namespaceKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UpdatedBy",
                    Size = 450,
                    Value = updatedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Note",
                    Size = 1000,
                    Value = note ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_BumpCacheNamespaceResult>("EXEC @returnValue = [rating].[usp_BumpCacheNamespace] @NamespaceKey = @NamespaceKey, @UpdatedBy = @UpdatedBy, @Note = @Note", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_BumpNamespacesForContractResult>?> usp_BumpNamespacesForContractAsync(long? contractId, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractId",
                    Value = contractId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Note",
                    Size = 1000,
                    Value = note ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_BumpNamespacesForContractResult>("EXEC @returnValue = [rating].[usp_BumpNamespacesForContract] @ContractId = @ContractId, @Note = @Note", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_BumpNamespacesForContractVersionResult>?> usp_BumpNamespacesForContractVersionAsync(long? contractVersionId, string? note, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractVersionId",
                    Value = contractVersionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Note",
                    Size = 1000,
                    Value = note ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_BumpNamespacesForContractVersionResult>("EXEC @returnValue = [rating].[usp_BumpNamespacesForContractVersion] @ContractVersionId = @ContractVersionId, @Note = @Note", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCacheNamespaceVersionResult>?> usp_GetCacheNamespaceVersionAsync(string? namespaceKey, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NamespaceKey",
                    Size = 400,
                    Value = namespaceKey ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCacheNamespaceVersionResult>("EXEC @returnValue = [rating].[usp_GetCacheNamespaceVersion] @NamespaceKey = @NamespaceKey", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCacheNamespaceVersionsForQuoteResult>?> usp_GetCacheNamespaceVersionsForQuoteAsync(long? accountId, string? mode, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AccountId",
                    Value = accountId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Mode",
                    Size = 20,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCacheNamespaceVersionsForQuoteResult>("EXEC @returnValue = [rating].[usp_GetCacheNamespaceVersionsForQuote] @AccountId = @AccountId, @Mode = @Mode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCandidateContractVersionsResult>?> usp_GetCandidateContractVersionsAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, string? equipmentType, string? containerType, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? originPort, string? destPort, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AccountId",
                    Value = accountId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Mode",
                    Size = 20,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RateDate",
                    Value = rateDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderIncludeCsv",
                    Size = -1,
                    Value = providerIncludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderExcludeCsv",
                    Size = -1,
                    Value = providerExcludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EquipmentType",
                    Size = 60,
                    Value = equipmentType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ContainerType",
                    Size = 40,
                    Value = containerType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OriginZoneId",
                    Value = originZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestZoneId",
                    Value = destZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OriginRegionId",
                    Value = originRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestRegionId",
                    Value = destRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OriginPort",
                    Size = 20,
                    Value = originPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DestPort",
                    Size = 20,
                    Value = destPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCandidateContractVersionsResult>("EXEC @returnValue = [rating].[usp_GetCandidateContractVersions] @AccountId = @AccountId, @Mode = @Mode, @RateDate = @RateDate, @ProviderIncludeCsv = @ProviderIncludeCsv, @ProviderExcludeCsv = @ProviderExcludeCsv, @EquipmentType = @EquipmentType, @ContainerType = @ContainerType, @OriginZoneId = @OriginZoneId, @DestZoneId = @DestZoneId, @OriginRegionId = @OriginRegionId, @DestRegionId = @DestRegionId, @OriginPort = @OriginPort, @DestPort = @DestPort", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCandidateContractVersions_ByLaneHashResult>?> usp_GetCandidateContractVersions_ByLaneHashAsync(long? accountId, string? mode, DateOnly? rateDate, byte[]? laneKeyHash, string? laneKeyString, string? providerIncludeCsv, string? providerExcludeCsv, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AccountId",
                    Value = accountId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Mode",
                    Size = 20,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RateDate",
                    Value = rateDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "LaneKeyHash",
                    Size = 32,
                    Value = laneKeyHash ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Binary,
                },
                new SqlParameter
                {
                    ParameterName = "LaneKeyString",
                    Size = 600,
                    Value = laneKeyString ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderIncludeCsv",
                    Size = -1,
                    Value = providerIncludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderExcludeCsv",
                    Size = -1,
                    Value = providerExcludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCandidateContractVersions_ByLaneHashResult>("EXEC @returnValue = [rating].[usp_GetCandidateContractVersions_ByLaneHash] @AccountId = @AccountId, @Mode = @Mode, @RateDate = @RateDate, @LaneKeyHash = @LaneKeyHash, @LaneKeyString = @LaneKeyString, @ProviderIncludeCsv = @ProviderIncludeCsv, @ProviderExcludeCsv = @ProviderExcludeCsv", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCandidateContractVersions_FastResult>?> usp_GetCandidateContractVersions_FastAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, string? equipmentType, string? containerType, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? originPort, string? destPort, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AccountId",
                    Value = accountId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Mode",
                    Size = 20,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RateDate",
                    Value = rateDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderIncludeCsv",
                    Size = -1,
                    Value = providerIncludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderExcludeCsv",
                    Size = -1,
                    Value = providerExcludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EquipmentType",
                    Size = 60,
                    Value = equipmentType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ContainerType",
                    Size = 40,
                    Value = containerType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OriginZoneId",
                    Value = originZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestZoneId",
                    Value = destZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OriginRegionId",
                    Value = originRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestRegionId",
                    Value = destRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OriginPort",
                    Size = 20,
                    Value = originPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DestPort",
                    Size = 20,
                    Value = destPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCandidateContractVersions_FastResult>("EXEC @returnValue = [rating].[usp_GetCandidateContractVersions_Fast] @AccountId = @AccountId, @Mode = @Mode, @RateDate = @RateDate, @ProviderIncludeCsv = @ProviderIncludeCsv, @ProviderExcludeCsv = @ProviderExcludeCsv, @EquipmentType = @EquipmentType, @ContainerType = @ContainerType, @OriginZoneId = @OriginZoneId, @DestZoneId = @DestZoneId, @OriginRegionId = @OriginRegionId, @DestRegionId = @DestRegionId, @OriginPort = @OriginPort, @DestPort = @DestPort", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetCandidateContractVersions_HashFastResult>?> usp_GetCandidateContractVersions_HashFastAsync(long? accountId, string? mode, DateOnly? rateDate, string? providerIncludeCsv, string? providerExcludeCsv, int? originZoneId, int? destZoneId, int? originRegionId, int? destRegionId, string? equipmentType, string? originPort, string? destPort, string? containerType, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "AccountId",
                    Value = accountId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "Mode",
                    Size = 20,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RateDate",
                    Value = rateDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderIncludeCsv",
                    Size = -1,
                    Value = providerIncludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ProviderExcludeCsv",
                    Size = -1,
                    Value = providerExcludeCsv ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OriginZoneId",
                    Value = originZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestZoneId",
                    Value = destZoneId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "OriginRegionId",
                    Value = originRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DestRegionId",
                    Value = destRegionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "EquipmentType",
                    Size = 60,
                    Value = equipmentType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OriginPort",
                    Size = 20,
                    Value = originPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DestPort",
                    Size = 20,
                    Value = destPort ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ContainerType",
                    Size = 40,
                    Value = containerType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetCandidateContractVersions_HashFastResult>("EXEC @returnValue = [rating].[usp_GetCandidateContractVersions_HashFast] @AccountId = @AccountId, @Mode = @Mode, @RateDate = @RateDate, @ProviderIncludeCsv = @ProviderIncludeCsv, @ProviderExcludeCsv = @ProviderExcludeCsv, @OriginZoneId = @OriginZoneId, @DestZoneId = @DestZoneId, @OriginRegionId = @OriginRegionId, @DestRegionId = @DestRegionId, @EquipmentType = @EquipmentType, @OriginPort = @OriginPort, @DestPort = @DestPort, @ContainerType = @ContainerType", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> usp_PublishContractVersionAsync(long? contractVersionId, string? publishedBy, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractVersionId",
                    Value = contractVersionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "PublishedBy",
                    Size = 200,
                    Value = publishedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [rating].[usp_PublishContractVersion] @ContractVersionId = @ContractVersionId, @PublishedBy = @PublishedBy", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_PublishContractVersion_HashResult>?> usp_PublishContractVersion_HashAsync(long? contractVersionId, string? publishedBy, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractVersionId",
                    Value = contractVersionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "PublishedBy",
                    Size = 200,
                    Value = publishedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_PublishContractVersion_HashResult>("EXEC @returnValue = [rating].[usp_PublishContractVersion_Hash] @ContractVersionId = @ContractVersionId, @PublishedBy = @PublishedBy", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> usp_RebuildContractLaneEligibilityAsync(long? contractVersionId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractVersionId",
                    Value = contractVersionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [rating].[usp_RebuildContractLaneEligibility] @ContractVersionId = @ContractVersionId", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> usp_RebuildContractLaneEligibility_HashAsync(long? contractVersionId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ContractVersionId",
                    Value = contractVersionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [rating].[usp_RebuildContractLaneEligibility_Hash] @ContractVersionId = @ContractVersionId", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
